<a href="https://colab.research.google.com/github/Ritesh-panda/Deep-learning/blob/main/DL_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
#importing the libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [53]:
df=pd.read_csv('/content/Churn_Modelling (2).csv')

In [54]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           9946 non-null   object
 6   Age              9700 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [56]:
#eliminate the row number
#eliminate the surname, customerid
df=df.drop(['RowNumber','CustomerId','Surname'], axis=1, errors='ignore')

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           9946 non-null   object
 3   Age              9700 non-null   float64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(3), int64(6), object(2)
memory usage: 859.5+ KB

In [58]:
#clear the empty value or null values
df=df.dropna(subset=['Age','Gender'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9662 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      9662 non-null   int64
 1   Geography        9662 non-null   object
 2   Gender           9662 non-null   object
 3   Age              9662 non-null   float64
 4   Tenure           9662 non-null   int64
 5   Balance          9662 non-null   float64
 6   NumOfProducts    9662 non-null   int64
 7   HasCrCard        9662 non-null   int64
 8   IsActiveMember   9662 non-null   int64
 9   EstimatedSalary  9662 non-null   float64
 10  Exited           9662 non-null   int64
dtypes: float64(3), int64(6), object(2)
memory usage: 905.8+ KB

In [59]:
df['Geography'].value_counts()
#here dummy encoding can be done as only 3 values are there

Geography
France     4847
Germany    2426
Spain      2389
Name: count, dtype: int64

In [60]:
df['HasCrCard'].value_counts()
#dummy encoding

HasCrCard
1    6816
0    2846
Name: count, dtype: int64

In [61]:
df['NumOfProducts'].value_counts()
#dummy encoding or one hot encoding

NumOfProducts
1    4915
2    4435
3     255
4      57
Name: count, dtype: int64

In [62]:
#dummy encoding on numof products,hascrcard,geography
df=pd.get_dummies(df, columns=['NumOfProducts','HasCrCard','Geography','Gender'])

In [63]:
df.head()

,CreditScore,Age,Tenure,Balance,IsActiveMember,EstimatedSalary,Exited,NumOfProducts_1,NumOfProducts_2,NumOfProducts_3,NumOfProducts_4,HasCrCard_0,HasCrCard_1,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42.0,2,0.00,1,101348.88,1,True,False,False,False,False,True,True,False,False,True,False
1,608,41.0,1,83807.86,1,112542.58,0,True,False,False,False,True,False,False,False,True,True,False
2,502,42.0,8,159660.80,0,113931.57,1,False,False,True,False,False,True,True,False,False,True,False
3,699,39.0,1,0.00,0,93826.63,0,False,True,False,False,True,False,True,False,False,True,False
4,850,43.0,2,125510.82,1,79084.10,0,True,False,False,False,False,True,False,False,True,True,False

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9662 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CreditScore        9662 non-null   int64
 1   Age                9662 non-null   float64
 2   Tenure             9662 non-null   int64
 3   Balance            9662 non-null   float64
 4   IsActiveMember     9662 non-null   int64
 5   EstimatedSalary    9662 non-null   float64
 6   Exited             9662 non-null   int64
 7   NumOfProducts_1    9662 non-null   bool
 8   NumOfProducts_2    9662 non-null   bool
 9   NumOfProducts_3    9662 non-null   bool
 10  NumOfProducts_4    9662 non-null   bool
 11  HasCrCard_0        9662 non-null   bool
 12  HasCrCard_1        9662 non-null   bool
 13  Geography_France   9662 non-null   bool
 14  Geography_Germany  9662 non-null   bool
 15  Geography_Spain    9662 non-null   bool
 16  Gender_Female      9662 non-null   bool
 17  Gender_Male        9662 non-null   bool
dtypes: bool(11), float64(3), int64(4)
memory usage: 707.7 KB

In [64]:
#train and test
from sklearn.model_selection import train_test_split
x=df.drop(['Exited'], axis=1)
y=df['Exited']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [66]:
#feature scaling in age,balance estimatesalary

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [68]:
from sklearn.tree import DecisionTreeClassifier
DT=DecisionTreeClassifier()
DT.fit(x_train,y_train)
y_pred=DT.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7988410596026491

In [70]:
#random forest
from sklearn.ensemble import RandomForestClassifier
RF=RandomForestClassifier(n_estimators=200)
RF.fit(x_train,y_train)
y_pred=RF.predict(x_test)
accuracy_score(y_test,y_pred)

0.8563741721854304

In [72]:
#ANN WILL BE DONE NOW ONWARDS
!pip install keras
!pip install tensorflow

Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras) (3.15.1)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras) (0.5.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras) (26.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from optree->keras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [75]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [84]:
classifier=Sequential()
"""
unis=input+output/2
initializer= how to update the weight
activation function= relu in input and hidden layers
and signoid at the output layer
input_dim= number of features
"""
#input layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=17))
#hidden layer 1
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
#hidden layer 2
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
#output layer
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [86]:

#COMPILING THE ANN
#binary_crossentropy as it is a binary cross entropy
#if categorical then categorical_crossentropy
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
y_train[0]
#fitting the dataset in the compiled model
classifier.fit(x_train,y_train,batch_size=10,epochs=200)

Epoch 1/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.8638 - loss: 0.3306
Epoch 2/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8666 - loss: 0.3271
Epoch 3/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8608 - loss: 0.3332
Epoch 4/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8634 - loss: 0.3346
Epoch 5/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8710 - loss: 0.3281
Epoch 6/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8752 - loss: 0.3170
Epoch 7/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8617 - loss: 0.3429
Epoch 8/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8721 - loss: 0.3141
Epoch 9/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.8612 - loss: 0.3346
Epoch 10/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8655 - loss: 0.3352
Epoch 11/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8619 - loss: 0.3315
Epoch 12/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8687 - loss: 0.3290
Epoch 13/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8635 - loss: 0.3219
Epoch 14/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8666 - loss: 0.3277
Epoch 15/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8649 - loss: 0.3362
Epoch 16/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8700 - loss: 0.3318
Epoch 17/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8645 - loss: 0.3352
Epoch 18/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8651 - loss: 0.3308
Epoch 19/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8624 - loss: 0.3349
Epoch 20/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8656 - loss: 0.3353
Epoch 21/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8679 - loss: 0.3290
Epoch 22/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8663 - loss: 0.3283
Epoch 23/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8652 - loss: 0.3350
Epoch 24/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8700 - loss: 0.3354
Epoch 25/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8665 - loss: 0.3301
Epoch 26/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8679 - loss: 0.3341
Epoch 27/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8630 - loss: 0.3386
Epoch 28/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8646 - loss: 0.3353
Epoch 29/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8765 - loss: 0.3197
Epoch 30/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8672 - loss: 0.3281
Epoch 31/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8679 - loss: 0.3225
Epoch 32/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8668 - loss: 0.3356
Epoch 33/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8700 - loss: 0.3241
Epoch 34/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8686 - loss: 0.3339
Epoch 35/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8703 - loss: 0.3269
Epoch 36/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8658 - loss: 0.3333
Epoch 37/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8659 - loss: 0.3377
Epoch 38/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8618 - loss: 0.3354
Epoch 39/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8657 - loss: 0.3282
Epoch 40/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8656 - loss: 0.3290
Epoch 41/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8787 - loss: 0.3115
Epoch 42/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8625 - loss: 0.3288
Epoch 43/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8616 - loss: 0.3372
Epoch 44/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8664 - loss: 0.3319
Epoch 45/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8533 - loss: 0.3417
Epoch 46/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8701 - loss: 0.3214
Epoch 47/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8639 - loss: 0.3275
Epoch 48/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8688 - loss: 0.3298
Epoch 49/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8552 - loss: 0.3464
Epoch 50/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8659 - loss: 0.3256
Epoch 51/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8689 - loss: 0.3323
Epoch 52/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8620 - loss: 0.3377
Epoch 53/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8716 - loss: 0.3212
Epoch 54/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8682 - loss: 0.3283
Epoch 55/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8653 - loss: 0.3323
Epoch 56/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8667 - loss: 0.3242
Epoch 57/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8682 - loss: 0.3259
Epoch 58/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8612 - loss: 0.3345
Epoch 59/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8614 - loss: 0.3370
Epoch 60/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8650 - loss: 0.3327
Epoch 61/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8725 - loss: 0.3230
Epoch 62/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8688 - loss: 0.3300
Epoch 63/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8634 - loss: 0.3383
Epoch 64/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8717 - loss: 0.3201
Epoch 65/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8699 - loss: 0.3218
Epoch 66/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8701 - loss: 0.3193
Epoch 67/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8596 - loss: 0.3417
Epoch 68/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8685 - loss: 0.3240
Epoch 69/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8626 - loss: 0.3382
Epoch 70/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8667 - loss: 0.3286
Epoch 71/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8652 - loss: 0.3367
Epoch 72/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8655 - loss: 0.3354
Epoch 73/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8698 - loss: 0.3238
Epoch 74/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8632 - loss: 0.3399
Epoch 75/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8696 - loss: 0.3320
Epoch 76/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8627 - loss: 0.3336
Epoch 77/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8608 - loss: 0.3349
Epoch 78/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8690 - loss: 0.3234
Epoch 79/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8648 - loss: 0.3369
Epoch 80/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8647 - loss: 0.3310
Epoch 81/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8652 - loss: 0.3234
Epoch 82/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8632 - loss: 0.3312
Epoch 83/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8675 - loss: 0.3271
Epoch 84/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8648 - loss: 0.3339
Epoch 85/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8644 - loss: 0.3283
Epoch 86/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8688 - loss: 0.3306
Epoch 87/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8691 - loss: 0.3208
Epoch 88/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8669 - loss: 0.3257
Epoch 89/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8674 - loss: 0.3266
Epoch 90/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8735 - loss: 0.3172
Epoch 91/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8592 - loss: 0.3385
Epoch 92/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8677 - loss: 0.3272
Epoch 93/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8665 - loss: 0.3265
Epoch 94/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8638 - loss: 0.3397
Epoch 95/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8708 - loss: 0.3185
Epoch 96/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8604 - loss: 0.3339
Epoch 97/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8665 - loss: 0.3321
Epoch 98/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8710 - loss: 0.3262
Epoch 99/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8692 - loss: 0.3191
Epoch 100/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8662 - loss: 0.3289
Epoch 101/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8604 - loss: 0.3385
Epoch 102/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8682 - loss: 0.3269
Epoch 103/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8650 - loss: 0.3230
Epoch 104/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8672 - loss: 0.3288
Epoch 105/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8674 - loss: 0.3329
Epoch 106/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8684 - loss: 0.3325
Epoch 107/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8618 - loss: 0.3264
Epoch 108/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8722 - loss: 0.3182
Epoch 109/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8646 - loss: 0.3281
Epoch 110/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8669 - loss: 0.3287
Epoch 111/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8620 - loss: 0.3364
Epoch 112/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8678 - loss: 0.3299
Epoch 113/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8604 - loss: 0.3405
Epoch 114/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8692 - loss: 0.3227
Epoch 115/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8748 - loss: 0.3230
Epoch 116/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8642 - loss: 0.3431
Epoch 117/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8585 - loss: 0.3418
Epoch 118/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8632 - loss: 0.3318
Epoch 119/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8678 - loss: 0.3201
Epoch 120/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8681 - loss: 0.3267
Epoch 121/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8557 - loss: 0.3409
Epoch 122/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8701 - loss: 0.3251
Epoch 123/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8691 - loss: 0.3256
Epoch 124/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8627 - loss: 0.3325
Epoch 125/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8623 - loss: 0.3377
Epoch 126/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8664 - loss: 0.3245
Epoch 127/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8676 - loss: 0.3333
Epoch 128/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8647 - loss: 0.3304
Epoch 129/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8670 - loss: 0.3269
Epoch 130/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8577 - loss: 0.3428
Epoch 131/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8701 - loss: 0.3233
Epoch 132/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8636 - loss: 0.3326
Epoch 133/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8629 - loss: 0.3296
Epoch 134/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8629 - loss: 0.3316
Epoch 135/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8664 - loss: 0.3270
Epoch 136/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8695 - loss: 0.3253
Epoch 137/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8617 - loss: 0.3355
Epoch 138/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8681 - loss: 0.3306
Epoch 139/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8696 - loss: 0.3297
Epoch 140/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8626 - loss: 0.3280
Epoch 141/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8636 - loss: 0.3338
Epoch 142/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8651 - loss: 0.3298
Epoch 143/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8706 - loss: 0.3236
Epoch 144/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8661 - loss: 0.3272
Epoch 145/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8654 - loss: 0.3219
Epoch 146/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8702 - loss: 0.3275
Epoch 147/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8649 - loss: 0.3344
Epoch 148/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8615 - loss: 0.3322
Epoch 149/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8732 - loss: 0.3266
Epoch 150/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8687 - loss: 0.3317
Epoch 151/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8668 - loss: 0.3273
Epoch 152/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8615 - loss: 0.3372
Epoch 153/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8613 - loss: 0.3352
Epoch 154/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8567 - loss: 0.3360
Epoch 155/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8710 - loss: 0.3205
Epoch 156/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8646 - loss: 0.3314
Epoch 157/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8723 - loss: 0.3171
Epoch 158/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8706 - loss: 0.3288
Epoch 159/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8689 - loss: 0.3240
Epoch 160/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8687 - loss: 0.3261
Epoch 161/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8686 - loss: 0.3230
Epoch 162/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8642 - loss: 0.3371
Epoch 163/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8640 - loss: 0.3300
Epoch 164/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8596 - loss: 0.3341
Epoch 165/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8646 - loss: 0.3393
Epoch 166/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8715 - loss: 0.3201
Epoch 167/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8604 - loss: 0.3395
Epoch 168/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8644 - loss: 0.3393
Epoch 169/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8715 - loss: 0.3147
Epoch 170/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8661 - loss: 0.3304
Epoch 171/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8580 - loss: 0.3408
Epoch 172/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8628 - loss: 0.3295
Epoch 173/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8717 - loss: 0.3247
Epoch 174/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8723 - loss: 0.3195
Epoch 175/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8636 - loss: 0.3353
Epoch 176/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8592 - loss: 0.3386
Epoch 177/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8610 - loss: 0.3363
Epoch 178/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8588 - loss: 0.3363
Epoch 179/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8683 - loss: 0.3283
Epoch 180/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8679 - loss: 0.3243
Epoch 181/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8647 - loss: 0.3330
Epoch 182/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8625 - loss: 0.3288
Epoch 183/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8670 - loss: 0.3277
Epoch 184/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8635 - loss: 0.3340
Epoch 185/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8638 - loss: 0.3288
Epoch 186/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8712 - loss: 0.3328
Epoch 187/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8657 - loss: 0.3397
Epoch 188/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8621 - loss: 0.3333
Epoch 189/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8596 - loss: 0.3372
Epoch 190/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8694 - loss: 0.3184
Epoch 191/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8631 - loss: 0.3401
Epoch 192/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8632 - loss: 0.3368
Epoch 193/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8704 - loss: 0.3232
Epoch 194/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8697 - loss: 0.3183
Epoch 195/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8685 - loss: 0.3240
Epoch 196/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8651 - loss: 0.3274
Epoch 197/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8652 - loss: 0.3320
Epoch 198/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8666 - loss: 0.3262
Epoch 199/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8632 - loss: 0.3356
Epoch 200/200
725/725 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8622 - loss: 0.3329

In [91]:
#making prediction and evaluating the model
y_pred=classifier.predict(x_test)
y_pred_ann=(y_pred>0.5)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_ann)
print(cm)

76/76 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[1834   82]
 [ 243  257]]

In [92]:
accuracy_score(y_test,y_pred_ann)

0.8654801324503312